// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAZmU7hCB4zoxdjme665rqqK4orDXKRFuI',
    appId: '1:530034374672:web:74cd3910f63aafb9bf3295',
    messagingSenderId: '530034374672',
    projectId: 'food-app-1995',
    authDomain: 'food-app-1995.firebaseapp.com',
    databaseURL: 'https://food-app-1995-default-rtdb.firebaseio.com',
    storageBucket: 'food-app-1995.appspot.com',
    measurementId: 'G-BBPVL1035F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCUq6qaFy0CfwjRFwD-N_Kuj0TFrhuJTgM',
    appId: '1:530034374672:android:5acd38607fb7e7fdbf3295',
    messagingSenderId: '530034374672',
    projectId: 'food-app-1995',
    databaseURL: 'https://food-app-1995-default-rtdb.firebaseio.com',
    storageBucket: 'food-app-1995.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA7lWYP51fLC8O_0rwBMDjGz5uNGN8-Ub8',
    appId: '1:530034374672:ios:c72d33104ce273eebf3295',
    messagingSenderId: '530034374672',
    projectId: 'food-app-1995',
    databaseURL: 'https://food-app-1995-default-rtdb.firebaseio.com',
    storageBucket: 'food-app-1995.appspot.com',
    iosBundleId: 'com.example.foodApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA7lWYP51fLC8O_0rwBMDjGz5uNGN8-Ub8',
    appId: '1:530034374672:ios:4abe4393226a2957bf3295',
    messagingSenderId: '530034374672',
    projectId: 'food-app-1995',
    databaseURL: 'https://food-app-1995-default-rtdb.firebaseio.com',
    storageBucket: 'food-app-1995.appspot.com',
    iosBundleId: 'com.example.foodApp.RunnerTests',
  );
}
